### ISSUE TITLE
Display question/issue

### ISSUE THREAD

**Issue by joey-spooner** [lmaccherone/Lumenize#74]
This is what I'm seeing (attached). Is that intentional or should the right column be visible? I'm using a larger than usual resolution.
![tool](https://cloud.githubusercontent.com/assets/225617/8042034/49330ef0-0dea-11e5-8489-7c13e8453f59.PNG)

**Comment by lmaccherone** [comment]
Yeah, I hadn't tested the layout with a variety of browsers and screen settings. 

I moved the "menu" of steps to the left. Let me know if that is any better. Also, you can find it at lumenize.com now instead of just maccherone.com/lumenize

BTW, I am reworking this entire thing to use virtual-dom and eliminate the flicker at each step. I'm also dropping Google Polymer in favor of Twitter Bootstrap, virtual-dom and the Zorium component system. The layout will be completely different then.
